// Generated by CoffeeScript 1.12.4
(function() {
  var A, e;

  A = [-7, 1, 5, 2, -4, 3, 0];

  e = function(anArray) {
    var i, j, k, left, length, ref, right, temp_a;
    length = anArray.length;
    temp_a = [];
    for (i = k = 0, ref = length; 0 <= ref ? k < ref : k > ref; i = 0 <= ref ? ++k : --k) {
      left = 0;
      right = 0;
      j = 0;
      while (j < i) {
        left += anArray[j];
        j++;
      }
      j = i + 1;
      while (j < length) {
        right += anArray[j];
        j++;
      }
      if (left === right) {
        temp_a.push(i);
      }
    }
    if (!!temp_a) {
      return temp_a;
    } else {
      return -1;
    }
  };

  console.log(e(A));

}).call(this);
